default: &default
  url: http://localhost:8123
  timeout: 60
  open_timeout: 3
  username: analytics
  password: admin

development:
  database: test_development
  <<: *default

test:
  database: test_test
  <<: *default

production:
  database: test
  <<: *default
