default: &default
  url: <%= ENV["CLICKHOUSE_URL"] %>
  username: <%= ENV["CLICKHOUSE_USERNAME"] %>
  password: <%= ENV["CLICKHOUSE_PASSWORD"] %>
  timeout: 60
  open_timeout: 3
  database: test

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: test_test
