default: &default
  url: http://localhost:8123
  timeout: 60
  open_timeout: 3
  username: analytics
  password: admin
  database: test

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  database: test_test
