default: &default
  url: http://localhost:8123
  timeout: 60
  open_timeout: 3
  username: analytics
  password: admin

development:
  <<: *default
  database: test_development

test:
  <<: *default
  database: test_test

production:
  <<: *default
  database: test
